<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Listing;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $this->call([
                        UserSeeder::class,
                        // ListingSeeder::class,
                    ]);

        Listing::insert([
            [
                "id"                   => 1,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "A Seeking Heart",
                "subtitle"             => "",
                "description"          => "Seventeen-year-old Samantha O'Brien runs away from her drunkard father in Wisconsin only to end up with a German-Mennonite family in Minnesota where she learns to trust and love again.",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://books.google.com/books/about/A_Seeking_Heart.html?hl=&id=ahI4R8PRngoC",
                "infoLink"             => "http://books.google.com/books?id=ahI4R8PRngoC&dq=inauthor:kim+vogel+Sawyer&hl=&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=ahI4R8PRngoC&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=1&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=ahI4R8PRngoC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2012",
                "created_at"           => "2024-04-23T12:24:32.000000Z",
                "updated_at"           => "2024-04-23T12:24:32.000000Z",
            ],
            [
                "id"                   => 2,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Just As I Am",
                "subtitle"             => "A Short Story Extra for What Once Was Lost",
                "description"          => "In this romantic 19th century-set short fiction follow-up to What Once Was Lost, while setting the stage for Sawyer's next novel, Echoes of Mercy, a young woman must let go of past rejections to find hope in the meaningful future God wants for her. Daisy Forrester has been raised in Brambleville, Kansas at Dunnigan's Orphan Asylum by Levi and Christina Jonnson. As she has watched younger, more appealing orphans come and go on to new families, Daisy has spent years becoming a valued helper for Ma and Pa Jonnson, as the orphans call them. However, she is coming up on her sixteenth birthday, and it will soon be time for her to make her own way in the world. Nervous about leaving the farm, she turns to the one connection she has out in the world--Robby, a friend who left the asylum before her and is now employed in Sinclair, Kansas at Dinsmore's World Famous Chocolate Factory. Daisy heads for the safe harbor that is his friendship, but the outside world doesn't offer the friendly welcome that Daisy dreams of and Robby faces unique challenges of his own in the form of an eager co-worker bent on sending Daisy back to Brambleville. Can Daisy look beyond her own insecurities to embrace a young man with great affection for her, and a God who calls her 'beloved'--just as she is?",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=2S85AAAAQBAJ",
                "infoLink"             => "https://play.google.com/store/books/details?id=2S85AAAAQBAJ&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=2S85AAAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=2&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=2S85AAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2013-11-19",
                "created_at"           => "2024-04-23T12:24:32.000000Z",
                "updated_at"           => "2024-04-23T12:24:32.000000Z",
            ],
            [
                "id"                   => 3,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Beginnings",
                "subtitle"             => "",
                "description"          => "Beth Quinn is struggling to find a place to belong in the Old Order Mennonite Community of Sommerfeld, Kansas. When she starts a business designing stained glass windows, two men-one a Mennonite, the other not-begin to vie for her attention. Andrew Braun, a member of the Sommerfeld fellowship, is dedicated to family and faith. Sean McCauley, the son of a successful businessman, may only be interested in Beth's talents. Will Beth look to her heavenly Father to fill the emptiness within, or will her desperate quest for love shatter more than one heart? Beginnings is book 2 in the Sommerfeld Trilogy. Other books in the trilogy include Bygones: Book 1 and Blessings: Book 3.",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=UFuCg91HTKcC",
                "infoLink"             => "https://play.google.com/store/books/details?id=UFuCg91HTKcC&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=UFuCg91HTKcC&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=3&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=UFuCg91HTKcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2009-08-01",
                "created_at"           => "2024-04-23T12:24:32.000000Z",
                "updated_at"           => "2024-04-23T12:24:32.000000Z",
            ],
            [
                "id"                   => 4,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Through the Deep Waters",
                "subtitle"             => "A Novel",
                "description"          => "A past filled with shame can be washed away with a love that conquers all Born to an unloving prostitute in a popular Chicago brothel, timid seventeen-year-old Dinah Hubley was raised amidst the secrets held in every dark, grimy room of her home. Anxious to escape, Dinah pursues her dream of becoming a Harvey Girl, waiting tables along the railroad in an upscale hotel. But when she finds out she isn’t old enough, her only option is to accept a job as a chambermaid at the Clifton Hotel in Florence, Kansas. Eager to put everything behind her, Dinah feels more worthless than ever, based on a single horrible decision she made to survive. The Clifton offers a life Dinah has never known, but blinded to the love around her, Dinah remains buried in the shame of her past. When a handsome chicken farmer named Amos Ackerman starts to show interest, Dinah withdraws further, convinced no one could want a sullied woman like her. Despite his self-consciousness about his handicapped leg and her strange behavior, Amos resolves to show Dinah Christ’s love. But can she ever accept a gift she so desperately needs?",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=NcQPAgAAQBAJ",
                "infoLink"             => "https://play.google.com/store/books/details?id=NcQPAgAAQBAJ&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=NcQPAgAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=4&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=NcQPAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2014-05-06",
                "created_at"           => "2024-04-23T12:24:32.000000Z",
                "updated_at"           => "2024-04-23T12:24:32.000000Z",
            ],
            [
                "id"                   => 5,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Bygones",
                "subtitle"             => "",
                "description"          => "Widower Marie Koeppler and her grown daughter Beth reluctantly return to the Mennonite community Marie abandoned twenty-three years ago. Soon after their arrival in Sommerfeld, a series of mysterious thefts raises the community's suspicions against the \"outsiders.\" Can Marie prove their innocence, or will she be forced to flee once more? Henry Braun thought he'd gotten his love for Marie out of his system, but soon begins to wonder if she's stolen more than his heart. When it's all said and done, can Henry and Marie let bygones be bygones, or has their love been doomed from the start? Bygones is book 1 in the Sommerfeld Trilogy. Other books in the trilogy include Beginnings: Book 2 and Blessings: Book 3.",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=4pggOU2DMh4C",
                "infoLink"             => "https://play.google.com/store/books/details?id=4pggOU2DMh4C&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=4pggOU2DMh4C&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=5&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=4pggOU2DMh4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2009-08-15",
                "created_at"           => "2024-04-23T12:24:32.000000Z",
                "updated_at"           => "2024-04-23T12:24:32.000000Z",
            ],
            [
                "id"                   => 6,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Unveiling the Past",
                "subtitle"             => "A Novel",
                "description"          => "Mysteries, family secrets, and the love of a true Father are found at the heart of this gripping novel from the bestselling author of Bringing Maggie Home Newlyweds Sean Eagle and Meghan DeFord are no strangers to pain and loss. As cold-case detectives, they know intimately the anguish family members endure after the murder or disappearance of a loved one. But when a new case hits too close to home, it threatens to pull loose the fragile cords of their young marriage. Sheila Menke was just a girl when her father left for work and never returned. An investigation revealed he had embezzled enough to start a new life elsewhere, but Sheila could never accept the court’s criminalization of her father. Meghan reluctantly takes the case, secretly fearing it will stir up buried feelings about her own biological father. And while Sean investigates the mysterious death of two young brothers, he longs to start a family. But Meghan worries that with a negligent mother and an absentee father as her parenting examples, she might never be fit for motherhood. As they delve deeper into the past, both Meghan and Sheila must choose to either stumble along the road of bitterness and resentment or walk the difficult path toward forgiveness and healing. When the cases begin to break wide open, these young women are poised to discover that while earthly fathers may fail, there is one in heaven who is a father to the fatherless.",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://books.google.com/books/about/Unveiling_the_Past.html?hl=&id=9uTcDwAAQBAJ",
                "infoLink"             => "http://books.google.com/books?id=9uTcDwAAQBAJ&dq=inauthor:kim+vogel+Sawyer&hl=&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=9uTcDwAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=6&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=9uTcDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2020-05-12",
                "created_at"           => "2024-04-23T12:24:32.000000Z",
                "updated_at"           => "2024-04-23T12:24:32.000000Z",
            ],
            [
                "id"                   => 7,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Still My Forever",
                "subtitle"             => "A Novel",
                "description"          => "Can a frustrated composer find new inspiration with the woman who once made his heart sing? From the bestselling author of Freedom’s Song comes a charming romance inspired by a real historical figure. “A melodious second-chance romance.”—Publishers Weekly Four years after leaving town to make a name for himself as a composer, Gilbert Baty has returned temporarily to Falke, Kansas. Now, he’s trying to keep everyone from learning the truth about his disastrous years in New York City. He hopes to start writing music again in Falke, but he can’t help being distracted by Ava Flaming, the brown-eyed baker to whom he was briefly engaged before he ended things—and who still stirs feelings in him he knows he has no right to pursue. Ava had thought she was past the loss of Gil Baty. But to her dismay, she’s as drawn to him as ever. The situation only gets worse when Gil establishes a youth band in Falke, showing once more what a good man he is. But when the band has a chance to compete in a statewide competition, Ava faces the prospect of heartbreak again. Could music take Gil away forever this time? Or might God be stirring in Ava’s and Gil’s hearts a new song that will draw them together for good?",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=T1FTEAAAQBAJ",
                "infoLink"             => "https://play.google.com/store/books/details?id=T1FTEAAAQBAJ&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=T1FTEAAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=7&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=T1FTEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2022-09-06",
                "created_at"           => "2024-04-23T12:24:32.000000Z",
                "updated_at"           => "2024-04-23T12:24:32.000000Z",
            ],
            [
                "id"                   => 8,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Echoes of Mercy",
                "subtitle"             => "A Novel",
                "description"          => "Sometimes a secret must be kept for the truth to be revealed. When a suspicious accident occurs at the famous Dinsmore Chocolate Factory in Sinclair, Kansas, Caroline Lang goes undercover as a factory worker to investigate the circumstances surrounding the event and how the factory treats its youngest employees—the child workers. Caroline’s fervent faith, her difficult childhood, and compassionate heart drove her to her job as an investigator for the Labor Commission and she is compelled to see children freed from such heavy adult responsibilities, to allow them to pursue an education. Oliver Dinsmore, heir to the Dinsmore candy dynasty, has his own investigation to conduct. Posing as a common worker known as “Ollie Moore,” he aims to find out all he can about the family business before he takes over for his father. Caroline and Oliver become fast friends, but tension mounts when the two find themselves at odds about the roles of child workers. Hiding their identities becomes even more difficult when fate brings them together over three children in desperate need. When all is revealed, will the truth destroy the love starting to grow between them?",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://books.google.com/books/about/Echoes_of_Mercy.html?hl=&id=A8hvDwAAQBAJ",
                "infoLink"             => "http://books.google.com/books?id=A8hvDwAAQBAJ&dq=inauthor:kim+vogel+Sawyer&hl=&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=A8hvDwAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=8&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=A8hvDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2014-01-21",
                "created_at"           => "2024-04-23T12:24:32.000000Z",
                "updated_at"           => "2024-04-23T12:24:32.000000Z",
            ],
            [
                "id"                   => 9,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Katy's Debate",
                "subtitle"             => "",
                "description"          => "Katy Lambright’s life transforms when she leaves the Mennonite school and enters a local high school. Is she prepared to face the secular world and teenage life beyond her community? New Club, New Crush ... New Mom? From bestselling fiction writer Kim Vogel Sawyer comes Katy’s Debate, the latest in the Katy Lambright series for young adults. Just as Katy is feeling settled in her new school, everything falls apart at home. Her father, believing she needs a mother, starts courting a woman Katy refuses to accept. Tensions rise as Katy schemes to send the woman packing. Meanwhile, the pressure builds at school as Katy joins the debate team, encounters a teammate’s scorn, and faces her growing feelings for a boy her father will never accept. Can Katy prove she doesn’t need a mother’s guidance even as she discovers more of what the world offers?",
                "categories"           => "Young Adult Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=HD_FWRrcBScC",
                "infoLink"             => "https://play.google.com/store/books/details?id=HD_FWRrcBScC&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=HD_FWRrcBScC&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=9&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=HD_FWRrcBScC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2010-05-25",
                "created_at"           => "2024-04-23T12:24:32.000000Z",
                "updated_at"           => "2024-04-23T12:24:32.000000Z",
            ],
            [
                "id"                   => 10,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "The Tapestry of Grace",
                "subtitle"             => "A Novel",
                "description"          => "When a group of Kansas women start a Frauenverein, a benevolent society devoted to aiding widows and orphans, life changes for more than just the hurting people they seek to help in this heartwarming romance inspired by historical events—from the bestselling author of Freedom’s Song. With classes paused for the planting season, Alexandertol’s schoolteacher Augusta Dyck is glad for some meaningful work to occupy her time. She even knows exactly who their town’s benevolence society should help first: quiet, reserved widower Konrad Rempel and his young twin sons. Konrad Rempel, however, is adamant that he doesn’t want help. His boys are mischievous but good-hearted. And though Konrad may be struggling, he doesn’t want anyone else sticking their nose in and telling him what his sons need. Or what he needs. For her part, the charity’s founder Martina Krahn is relieved to have a reason to spend time outside her unhappy home. It even occurs to her that she may, through her work, encounter a boy in need of a family and so find a son for her husband since they have no children of their own. Augusta, Konrad, and Martina each have deep needs and desires, and each imagines how they should be met: by reaching out or by being left alone. But God, indeed, knows best. Will the competing agendas of Alexandertol’s residents prevent them from receiving God’s help? Or will the members of this small Mennonite community find the answers to their prayers in the very last place they expect—in one another?",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=Kwp8EAAAQBAJ",
                "infoLink"             => "https://play.google.com/store/books/details?id=Kwp8EAAAQBAJ&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=Kwp8EAAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=10&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=Kwp8EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2023-04-18",
                "created_at"           => "2024-04-23T12:24:32.000000Z",
                "updated_at"           => "2024-04-23T12:24:32.000000Z",
            ],
            [
                "id"                   => 11,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "A Seeking Heart",
                "subtitle"             => "",
                "description"          => "Seventeen-year-old Samantha O'Brien runs away from her drunkard father in Wisconsin only to end up with a German-Mennonite family in Minnesota where she learns to trust and love again.",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://books.google.com/books/about/A_Seeking_Heart.html?hl=&id=ahI4R8PRngoC",
                "infoLink"             => "http://books.google.com/books?id=ahI4R8PRngoC&dq=inauthor:kim+vogel+Sawyer&hl=&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=ahI4R8PRngoC&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=1&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=ahI4R8PRngoC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2012",
                "created_at"           => "2024-04-23T19:38:26.000000Z",
                "updated_at"           => "2024-04-23T19:38:26.000000Z",
            ],
            [
                "id"                   => 12,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Just As I Am",
                "subtitle"             => "A Short Story Extra for What Once Was Lost",
                "description"          => "In this romantic 19th century-set short fiction follow-up to What Once Was Lost, while setting the stage for Sawyer's next novel, Echoes of Mercy, a young woman must let go of past rejections to find hope in the meaningful future God wants for her. Daisy Forrester has been raised in Brambleville, Kansas at Dunnigan's Orphan Asylum by Levi and Christina Jonnson. As she has watched younger, more appealing orphans come and go on to new families, Daisy has spent years becoming a valued helper for Ma and Pa Jonnson, as the orphans call them. However, she is coming up on her sixteenth birthday, and it will soon be time for her to make her own way in the world. Nervous about leaving the farm, she turns to the one connection she has out in the world--Robby, a friend who left the asylum before her and is now employed in Sinclair, Kansas at Dinsmore's World Famous Chocolate Factory. Daisy heads for the safe harbor that is his friendship, but the outside world doesn't offer the friendly welcome that Daisy dreams of and Robby faces unique challenges of his own in the form of an eager co-worker bent on sending Daisy back to Brambleville. Can Daisy look beyond her own insecurities to embrace a young man with great affection for her, and a God who calls her 'beloved'--just as she is?",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=2S85AAAAQBAJ",
                "infoLink"             => "https://play.google.com/store/books/details?id=2S85AAAAQBAJ&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=2S85AAAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=2&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=2S85AAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2013-11-19",
                "created_at"           => "2024-04-23T19:38:26.000000Z",
                "updated_at"           => "2024-04-23T19:38:26.000000Z",
            ],
            [
                "id"                   => 13,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Through the Deep Waters",
                "subtitle"             => "A Novel",
                "description"          => "A past filled with shame can be washed away with a love that conquers all Born to an unloving prostitute in a popular Chicago brothel, timid seventeen-year-old Dinah Hubley was raised amidst the secrets held in every dark, grimy room of her home. Anxious to escape, Dinah pursues her dream of becoming a Harvey Girl, waiting tables along the railroad in an upscale hotel. But when she finds out she isn’t old enough, her only option is to accept a job as a chambermaid at the Clifton Hotel in Florence, Kansas. Eager to put everything behind her, Dinah feels more worthless than ever, based on a single horrible decision she made to survive. The Clifton offers a life Dinah has never known, but blinded to the love around her, Dinah remains buried in the shame of her past. When a handsome chicken farmer named Amos Ackerman starts to show interest, Dinah withdraws further, convinced no one could want a sullied woman like her. Despite his self-consciousness about his handicapped leg and her strange behavior, Amos resolves to show Dinah Christ’s love. But can she ever accept a gift she so desperately needs?",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=NcQPAgAAQBAJ",
                "infoLink"             => "https://play.google.com/store/books/details?id=NcQPAgAAQBAJ&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=NcQPAgAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=3&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=NcQPAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2014-05-06",
                "created_at"           => "2024-04-23T19:38:26.000000Z",
                "updated_at"           => "2024-04-23T19:38:26.000000Z",
            ],
            [
                "id"                   => 14,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Beginnings",
                "subtitle"             => "",
                "description"          => "Beth Quinn is struggling to find a place to belong in the Old Order Mennonite Community of Sommerfeld, Kansas. When she starts a business designing stained glass windows, two men-one a Mennonite, the other not-begin to vie for her attention. Andrew Braun, a member of the Sommerfeld fellowship, is dedicated to family and faith. Sean McCauley, the son of a successful businessman, may only be interested in Beth's talents. Will Beth look to her heavenly Father to fill the emptiness within, or will her desperate quest for love shatter more than one heart? Beginnings is book 2 in the Sommerfeld Trilogy. Other books in the trilogy include Bygones: Book 1 and Blessings: Book 3.",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=UFuCg91HTKcC",
                "infoLink"             => "https://play.google.com/store/books/details?id=UFuCg91HTKcC&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=UFuCg91HTKcC&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=4&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=UFuCg91HTKcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2009-08-01",
                "created_at"           => "2024-04-23T19:38:26.000000Z",
                "updated_at"           => "2024-04-23T19:38:26.000000Z",
            ],
            [
                "id"                   => 15,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Bygones",
                "subtitle"             => "",
                "description"          => "Widower Marie Koeppler and her grown daughter Beth reluctantly return to the Mennonite community Marie abandoned twenty-three years ago. Soon after their arrival in Sommerfeld, a series of mysterious thefts raises the community's suspicions against the \"outsiders . \" Can Marie prove their innocence, or will she be forced to flee once more? Henry Braun thought he'd gotten his love for Marie out of his system, but soon begins to wonder if she's stolen more than his heart. When it's all said and done, can Henry and Marie let bygones be bygones, or has their love been doomed from the start? Bygones is book 1 in the Sommerfeld Trilogy. Other books in the trilogy include Beginnings: Book 2 and Blessings: Book 3.",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=4pggOU2DMh4C",
                "infoLink"             => "https://play.google.com/store/books/details?id=4pggOU2DMh4C&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=4pggOU2DMh4C&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=5&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=4pggOU2DMh4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2009-08-15",
                "created_at"           => "2024-04-23T19:38:26.000000Z",
                "updated_at"           => "2024-04-23T19:38:26.000000Z",
            ],
            [
                "id"                   => 16,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Unveiling the Past",
                "subtitle"             => "A Novel",
                "description"          => "Mysteries, family secrets, and the love of a true Father are found at the heart of this gripping novel from the bestselling author of Bringing Maggie Home Newlyweds Sean Eagle and Meghan DeFord are no strangers to pain and loss. As cold-case detectives, they know intimately the anguish family members endure after the murder or disappearance of a loved one. But when a new case hits too close to home, it threatens to pull loose the fragile cords of their young marriage. Sheila Menke was just a girl when her father left for work and never returned. An investigation revealed he had embezzled enough to start a new life elsewhere, but Sheila could never accept the court’s criminalization of her father. Meghan reluctantly takes the case, secretly fearing it will stir up buried feelings about her own biological father. And while Sean investigates the mysterious death of two young brothers, he longs to start a family. But Meghan worries that with a negligent mother and an absentee father as her parenting examples, she might never be fit for motherhood. As they delve deeper into the past, both Meghan and Sheila must choose to either stumble along the road of bitterness and resentment or walk the difficult path toward forgiveness and healing. When the cases begin to break wide open, these young women are poised to discover that while earthly fathers may fail, there is one in heaven who is a father to the fatherless.",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://books.google.com/books/about/Unveiling_the_Past.html?hl=&id=9uTcDwAAQBAJ",
                "infoLink"             => "http://books.google.com/books?id=9uTcDwAAQBAJ&dq=inauthor:kim+vogel+Sawyer&hl=&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=9uTcDwAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=6&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=9uTcDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2020-05-12",
                "created_at"           => "2024-04-23T19:38:26.000000Z",
                "updated_at"           => "2024-04-23T19:38:26.000000Z",
            ],
            [
                "id"                   => 17,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Still My Forever",
                "subtitle"             => "A Novel",
                "description"          => "Can a frustrated composer find new inspiration with the woman who once made his heart sing? From the bestselling author of Freedom’s Song comes a charming romance inspired by a real historical figure. “A melodious second-chance romance.”—Publishers Weekly Four years after leaving town to make a name for himself as a composer, Gilbert Baty has returned temporarily to Falke, Kansas. Now, he’s trying to keep everyone from learning the truth about his disastrous years in New York City. He hopes to start writing music again in Falke, but he can’t help being distracted by Ava Flaming, the brown-eyed baker to whom he was briefly engaged before he ended things—and who still stirs feelings in him he knows he has no right to pursue. Ava had thought she was past the loss of Gil Baty. But to her dismay, she’s as drawn to him as ever. The situation only gets worse when Gil establishes a youth band in Falke, showing once more what a good man he is. But when the band has a chance to compete in a statewide competition, Ava faces the prospect of heartbreak again. Could music take Gil away forever this time? Or might God be stirring in Ava’s and Gil’s hearts a new song that will draw them together for good?",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=T1FTEAAAQBAJ",
                "infoLink"             => "https://play.google.com/store/books/details?id=T1FTEAAAQBAJ&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=T1FTEAAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=7&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=T1FTEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2022-09-06",
                "created_at"           => "2024-04-23T19:38:26.000000Z",
                "updated_at"           => "2024-04-23T19:38:26.000000Z",
            ],
            [
                "id"                   => 18,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Echoes of Mercy",
                "subtitle"             => "A Novel",
                "description"          => "Sometimes a secret must be kept for the truth to be revealed. When a suspicious accident occurs at the famous Dinsmore Chocolate Factory in Sinclair, Kansas, Caroline Lang goes undercover as a factory worker to investigate the circumstances surrounding the event and how the factory treats its youngest employees—the child workers. Caroline’s fervent faith, her difficult childhood, and compassionate heart drove her to her job as an investigator for the Labor Commission and she is compelled to see children freed from such heavy adult responsibilities, to allow them to pursue an education. Oliver Dinsmore, heir to the Dinsmore candy dynasty, has his own investigation to conduct. Posing as a common worker known as “Ollie Moore,” he aims to find out all he can about the family business before he takes over for his father. Caroline and Oliver become fast friends, but tension mounts when the two find themselves at odds about the roles of child workers. Hiding their identities becomes even more difficult when fate brings them together over three children in desperate need. When all is revealed, will the truth destroy the love starting to grow between them?",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://books.google.com/books/about/Echoes_of_Mercy.html?hl=&id=A8hvDwAAQBAJ",
                "infoLink"             => "http://books.google.com/books?id=A8hvDwAAQBAJ&dq=inauthor:kim+vogel+Sawyer&hl=&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=A8hvDwAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=8&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=A8hvDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2014-01-21",
                "created_at"           => "2024-04-23T19:38:26.000000Z",
                "updated_at"           => "2024-04-23T19:38:26.000000Z",
            ],
            [
                "id"                   => 19,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "Katy's Debate",
                "subtitle"             => "",
                "description"          => "Katy Lambright’s life transforms when she leaves the Mennonite school and enters a local high school. Is she prepared to face the secular world and teenage life beyond her community? New Club, New Crush ... New Mom? From bestselling fiction writer Kim Vogel Sawyer comes Katy’s Debate, the latest in the Katy Lambright series for young adults. Just as Katy is feeling settled in her new school, everything falls apart at home. Her father, believing she needs a mother, starts courting a woman Katy refuses to accept. Tensions rise as Katy schemes to send the woman packing. Meanwhile, the pressure builds at school as Katy joins the debate team, encounters a teammate’s scorn, and faces her growing feelings for a boy her father will never accept. Can Katy prove she doesn’t need a mother’s guidance even as she discovers more of what the world offers?",
                "categories"           => "Young Adult Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=HD_FWRrcBScC",
                "infoLink"             => "https://play.google.com/store/books/details?id=HD_FWRrcBScC&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=HD_FWRrcBScC&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=9&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=HD_FWRrcBScC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2010-05-25",
                "created_at"           => "2024-04-23T19:38:26.000000Z",
                "updated_at"           => "2024-04-23T19:38:26.000000Z",
            ],
            [
                "id"                   => 20,
                "authors"              => "Kim Vogel Sawyer",
                "title"                => "The Tapestry of Grace",
                "subtitle"             => "A Novel",
                "description"          => "When a group of Kansas women start a Frauenverein, a benevolent society devoted to aiding widows and orphans, life changes for more than just the hurting people they seek to help in this heartwarming romance inspired by historical events—from the bestselling author of Freedom’s Song. With classes paused for the planting season, Alexandertol’s schoolteacher Augusta Dyck is glad for some meaningful work to occupy her time. She even knows exactly who their town’s benevolence society should help first: quiet, reserved widower Konrad Rempel and his young twin sons. Konrad Rempel, however, is adamant that he doesn’t want help. His boys are mischievous but good-hearted. And though Konrad may be struggling, he doesn’t want anyone else sticking their nose in and telling him what his sons need. Or what he needs. For her part, the charity’s founder Martina Krahn is relieved to have a reason to spend time outside her unhappy home. It even occurs to her that she may, through her work, encounter a boy in need of a family and so find a son for her husband since they have no children of their own. Augusta, Konrad, and Martina each have deep needs and desires, and each imagines how they should be met: by reaching out or by being left alone. But God, indeed, knows best. Will the competing agendas of Alexandertol’s residents prevent them from receiving God’s help? Or will the members of this small Mennonite community find the answers to their prayers in the very last place they expect—in one another?",
                "categories"           => "Fiction",
                "canonicalVolumeLink"  => "https://play.google.com/store/books/details?id=Kwp8EAAAQBAJ",
                "infoLink"             => "https://play.google.com/store/books/details?id=Kwp8EAAAQBAJ&source=gbs_api",
                "previewLink"          => "http://books.google.com/books?id=Kwp8EAAAQBAJ&printsec=frontcover&dq=inauthor:kim+vogel+Sawyer&hl=&cd=10&source=gbs_api",
                "imageLinks_thumbnail" => "http://books.google.com/books/content?id=Kwp8EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                "publishedDate"        => "2023-04-18",
                "created_at"           => "2024-04-23T19:38:26.000000Z",
                "updated_at"           => "2024-04-23T19:38:26.000000Z",
            ],
        ]);
    }
}
